### ISSUE TITLE
When click and expand row after getting an http request the colspan changes to one

### ISSUE THREAD

**Issue by alcazardaas** [react-bootstrap-table/react-bootstrap-table2#1322] opened 2020-04-07 18:13 UTC
**Question**
When the table loads the data and I click over a row, it makes a request for the data. It shows well with two colspan, but just after the response arrives it change the colspan to one
How can I fix this?  There is any related data or issue?

**Edit**: If I close the expanded row and expand it once again it shows the two colspan (it doesn't make a new request if the data in memory)

**Libraries**
-     "react-bootstrap-table-next": "^3.0.1",
-     "react-bootstrap-table2-filter": "^1.1.6",
-     "react-bootstrap-table2-paginator": "^2.0.4",
-     "react-bootstrap-table2-toolkit": "^1.3.2",

**Screenshots**
This is just after clicking the row
![image](https://user-images.githubusercontent.com/17205012/78703752-fd32a080-78c7-11ea-8f0d-eb88ba69ace4.png)

When the request respond it change the colspan to one
![image](https://user-images.githubusercontent.com/17205012/78703663-d70d0080-78c7-11ea-85a5-073cc0a79b1d.png)

**code**
`const rowEvents = {
    onClick: (e, row) => {
         getExpandableGroup(`${row.guid}`); //gets data to be shown at the expandable
     }
  }`

`const expandRow = {
    renderer: row => {
       return (
           <div>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis, provident. Quos odio 
                dolores cum eum sapiente odit doloribus reprehenderit quod modi aut tempore error, 
                 quae placeat ratione autem dolor dicta!
                 Quidem consequuntur voluptates iusto fuga nobis, quo deserunt sapiente magni eaque 
                 molestiae, perspiciatis iure natus tenetur animi. Amet dolorum distinctio, quibusdam 
                   doloribus praesentium nam a quisquam debitis fugit tempora totam?
                 Natus nobis, ut harum nostrum eligendi eos excepturi magni reprehenderit. Quae error 
                 illo labore consectetur, unde placeat magnam obcaecati cumque non reiciendis sed 
                 officiis accusamus, quaerat, in architecto dolorum accusantium.
       </div>)
    },
    showExpandColumn: true
  };`

**Comment by AllenFang** [comment] 2020-04-11 08:07
@alcazardaas please follow the instruction to create an issue. "Give an exampl on code sandbox, so that I can help you and reproduce your issue efficiently" (Keep the code simple and minimal)

thanks. Just close it due to not enough information and let's wait your another issue.

**Closed by AllenFang** 2020-04-11 08:07 UTC
