### ISSUE TITLE
[HELP WANTED] Calculate totals and averages

### ISSUE THREAD

**Issue by tylerkeesling** [react-bootstrap-table/react-bootstrap-table2#121] opened 2017-10-27 01:17 UTC
Is there anyway to calculate totals or averages for a single column and display those values at the bottom of the chart?

**Comment by prajapati-parth** [comment] 2017-10-27 05:01
Hello @tylerkeesling, react-bootstrap-table2 will support a footer feature where these data can be displayed. https://github.com/react-bootstrap-table/react-bootstrap-table2#react-bootstrap-table2

But currently the focus is on completing basic table features so it'll take some time.

**Comment by AllenFang** [comment] 2017-10-28 13:22
Like @prajapati-parth mentioned above, we must support the table footer and it's sorry that we dont have nice footer support on react-bootstrap-table.  Please keep to follow our achievements in near future.  Thanks

**Comment by AllenFang** [comment] 2017-10-28 13:22
Close it due to duplicated

**Closed by AllenFang** 2017-10-28 13:22 UTC

**Comment by Camphor-Tree** [comment] 2018-10-10 17:46
The issue #2 is also resolved due to duplicate of this issue. There is a loop : )

Do we have footer or summary row support now?

**Comment by prajapati-parth** [comment] 2018-10-10 17:50
@Camphor-Tree
issue #2 has open status.

**Comment by AllenFang** [comment] 2019-01-20 14:54
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/01/20/version-bump.html

release on `react-bootstrap-table-next@2.1.0`
check [these](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Footer&selectedStory=Simple%20Footer&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) examples
