### ISSUE TITLE
Can't display boolean value

### ISSUE THREAD

**Issue by ngohungphuc** [react-bootstrap-table/react-bootstrap-table2#295] opened 2018-04-07 04:22 UTC
I have this piece of data

![chrome_2018-04-07_11-21-37](https://user-images.githubusercontent.com/13591213/38451198-d68bed2c-3a55-11e8-9ccf-b217ce3c9884.png)

My setup
```js
const columns = [
      {
        dataField: "userName",
        text: "UserName",
        sort: true
      },
      {
        dataField: "email",
        text: "Email",
        sort: true
      },
      {
        dataField: "emailConfirmed",
        text: "EmailConfirmed",
        sort: true
     },
      {
        dataField: "roles",
        text: "Roles"
      }
    ];
    return (
      <BootstrapTable
        classes="table table-sm table-hover table-bordered table-striped table-dark"
        keyField="userId"
        data={userList}
        columns={columns}
      />
    );
```

The result and is seem like i cant display boolean value. Am I missing something ?

![chrome_2018-04-07_11-22-21](https://user-images.githubusercontent.com/13591213/38451201-f4a2fb5c-3a55-11e8-90ea-b388ce342661.png)

**Comment by Chun-MingChen** [comment] 2018-04-07 16:28
This is not a bug. Hence close this issue.

**Closed by Chun-MingChen** 2018-04-07 16:28 UTC
