### ISSUE TITLE
Calling this.setState() in onSelect handler disables checkbox toggle

### ISSUE THREAD

**Issue by Ignalion** [react-bootstrap-table/react-bootstrap-table2#411] opened 2018-07-13 21:33 UTC
Hi, @AllenFang 

The issue is the following. This code works:

```
class App extends React.Component {
    constructor(props) {
        super(props);
        this.state = {value: ''};
        this.onSelectionChanged = this.onSelectionChanged.bind(this)
    }

    onSelectionChanged (row, isSelect, rowIndex, e) {
        console.log(this.state.value);
    }

    render () {
        const selectRow = {mode: 'checkbox', onSelect: this.onSelectionChanged};
        return (
        <BootstrapTable selectRow={selectRow} keyField='id' data={products} columns={columns}/>
        )
    }
}
```

(products and columns can be taken from docs example for instance)

However if you change console.log to, let's say, this:

```
    onSelectionChanged (row, isSelect, rowIndex, e) {
        this.setState({value: ''});
    }
```

then selection is broken.

As per my investigation, it happens because react keeps incorrect state of checkbox (checked: false) and in restoreStateOfTarget is restoring its unchecked state.

Unfortunately my understanding of React isn't that good to find a root cause so I'll appreciate your help in this issue.

**Comment by AllenFang** [comment] 2018-07-14 04:33
@Ignalion please check https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/411

Right now the workaround is you have to manage the selection. I will enhance it in the future.

Close it due to duplicated.

**Closed by AllenFang** 2018-07-14 04:33 UTC

**Comment by AllenFang** [comment] 2018-11-04 16:29
Sorry for lately fixed.....
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/11/04/version.bump.html)

now you can call `setState` in `selectRow.onSelect` and we support a feature that you can reject the selection, please check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-select-props.html#selectrowonselect-function) and [here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Advance%20Selection%20Management&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is example

**Comment by ghettosunrise** [comment] 2021-02-12 17:42
@AllenFang the same with me. If i use setState inside onSelect function - it breaks custom style of selected row and checkboxes

**Comment by vincepunkrock** [comment] 2021-11-23 18:20
@AllenFang It seems the problem with setState still persists in version 4.0.3. I had to use the workaround mentioned in [#297](https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/297) to make it work. Possible regression since [react-bootstrap-table-next@1.4.0](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/11/04/version.bump.html) ?
