### ISSUE TITLE
setState not re rendering in version ^1.0.0

### ISSUE THREAD

**Issue by dpramani** [react-bootstrap-table/react-bootstrap-table2#504] opened 2018-08-21 16:41 UTC
Hi @AllenFang 

I have a function which simply sets the state of a variable, based on the row index. **Version 1.0.0 works perfectly with the code**. But when I installed the new version ^1.0.0, it somehow stops rendering. It sets the state of the variable, but doesn't re render.  I will provide some code snippets to back this issue. 

**Note : Basically the column formatter method is not getting called.**  (No error in console)

Thanks
The div that has a onClick handler:

           <div
            role="button"
            tabIndex="0"
            onKeyDown={() => this.handleSettings(rowIndex)}
            className={gearIconWrapper ${showGearOptions}}
            onClick={() => this.handleSettings(rowIndex)}
          >
The function that's setting the state, but not re rendering : 

`this.handleSettings = this.handleSettings.bind(this);`
  `handleSettings(rowIndex) 
  {
      this.setState({
      activeIndex: rowIndex, });
 }`

**Comment by AllenFang** [comment] 2018-08-23 15:17
@dpramani firstly could you please make sure what version u used now?

secondly, please show me the code of `column.formatter`. In addition, please check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnformatter-function) and be carefully on "Attention" part.  Because after [`1.1.0`](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/08/12/version-bump.html) we improve the performance of cell level rendering.

**Comment by waynebrantley** [comment] 2018-08-29 14:33
I can confirm this.  
https://codesandbox.io/s/4zkpv0n4ww

In this example, click the button and you will see that only the 3rd column will re-render.
However, if I make the datafield="inStock" for the last column and blank for 3rd column - then the 4th column will re-render, but not the 3rd column.

Only the column named 'instock' will be updated.  I cannot name them both instock as an error will occur.  Additionally, the logic in the formatter could rely on several fields

**Comment by AllenFang** [comment] 2018-09-01 04:47
@waynebrantley this is probably special case, I will look into your case. Thank you for providing this issue.

**Comment by waynebrantley** [comment] 2018-09-02 01:14
@AllenFang thanks for fixing.  Of note - if there are several dummy or calculated columns, we have to make up 'fake field names' as you require the field names to be unique.  So only one "" column is allowed.

Additionally, you could add an optional 'shouldCellUpdate' for a column - you could pass current and next row into it...we could return true/false based on whatever logic - thereby optimizing the rendering.

**Comment by AllenFang** [comment] 2018-09-03 14:38
@waynebrantley 


> if there are several dummy or calculated columns, we have to make up 'fake field names' as you require the field names to be unique. So only one "" column is allowed.

yes, in the patch, `dataField` can be anything, but just keep it unique when u assign the `isDummyField` as true



> Additionally, you could add an optional 'shouldCellUpdate' for a column - you could pass current and next row into it...we could return true/false based on whatever logic

That could be a good idea. Currently, we have some optimizing on cell level component, that's already enough. But I think I have to think about the timing for using `shouldCellUpdate` option.  Anyway, it's good idea.

BTW, this issue will be fixed later. Wait my signal, thank you

**Closed** 2018-09-03 15:26 UTC
Labels: enhancement

**Comment by AllenFang** [comment] 2018-09-03 15:43
@waynebrantley 

[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/09/03/version-bump.html

[YOUR EXAMPLE](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Work%20on%20Columns&selectedStory=Dummy%20Column&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) . 

Please upgrade related packages to newest version, thanks

**Comment by waynebrantley** [comment] 2018-09-05 02:31
@AllenFang Thanks!
