### ISSUE TITLE
Select rows - check box isn't working good

### ISSUE THREAD

**Issue by avichaigrunseid** [react-bootstrap-table/react-bootstrap-table2#1219] opened 2020-01-02 15:48 UTC
hi,

I'm using:

const selectRow = {
                mode: 'checkbox',
                clickToSelect: true
              };

 <BootstrapTable  {...props.baseProps} keyField='id'    data={products} columns={columns}  selectRow={selectRow}    />    bootstrap table 

the check box method isnt working good and isnt in the correct position in the table.
![image](https://user-images.githubusercontent.com/53261178/71676037-d07e6280-2d87-11ea-9050-9b780dd10a20.png)

when clicking on the table I'm getting all the checkbox to marked.

**Comment by gsunsnackv** [comment] 2020-01-13 18:34
I got the same issue until I figured out that `keyField='id'` is important. Turns out my data does not have id but objectId, so I changed to `keyField='objectId'` and then it starts to work. The documentation here https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-select-props.html#selectrowmode-string should mention it

**Comment by avichaigrunseid** [comment] 2020-01-18 19:03
Hi ,

ive changed my code to:

 <ToolkitProvider keyField='objectId'
        data={products}
        columns={columns}
        columnToggle
        cellEdit
        search >

        {
            (props: { csvProps: JSX.IntrinsicAttributes; searchProps: JSX.
IntrinsicAttributes; baseProps: JSX.IntrinsicAttributes; }) => (
                <div>

                            <hr />
                            <MySearch {...props.searchProps} id="SearchBar"
/>
                            <br></br>

                        <BootstrapTable  {...props.baseProps} keyField=
'objectId'
                           data={products} columns={columns}     selectRow={
 selectRow }
                           cellEdit={ cellEditFactory({
                            mode: 'click',
                            blurToSave: true,
                            nonEditableRows: () => [0, 6],
                          }) }
                         />
                </div>
             )
        }

         </ToolkitProvider>
         </div>


and it's still not working!

Thanks

**Comment by AllenFang** [comment] 2020-02-09 08:26
`keyfield` should be unique. close it due to can't reproduce. Please share a an example on codesandbox so that I can debug if the problem still remain

**Closed by AllenFang** 2020-02-09 08:26 UTC

**Comment by gsunsnackv** [comment] 2020-02-10 03:00
@AllenFang Can we update the doc to mention that "keyfield should be unique"?

https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-select-props.html#selectrowmode-string
