### ISSUE TITLE
Size Per Page Drop Down not working

### ISSUE THREAD

**Issue by lilucanalplus** [react-bootstrap-table/react-bootstrap-table2#178] opened 2018-01-23 14:06 UTC
Lately I've started to try this second version of react bootstrap table, but I've met a same issue as #710 and #539 for react-bootstrap-table (drop down list does not appear), mean while I've well added the bootstrap and also jquery, but the drop down menu still dosen't appear while clicking on the button of dropdown.

Thanks in advance for your help.

**Comment by AllenFang** [comment] 2018-01-23 15:44
@lilucanalplus let's focus on following check list

1. Do you import the `react-bootstrap-table2-paginator.min.css`?
2. Actually, `react-bootstrap-table2` only need the `bootstrap.min.css`
3. What's the version of bootstrap, currently, bootstrap@4 not yet supported.

I think there's not a bug, the [online](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Pagination) demo work great. 

Maybe you can give me a **simple** and **minimal** repo to reproduce it. thanks

**Comment by AllenFang** [comment] 2018-01-23 15:45
Let close it firstly due to can't identify the root cause, will open again if we can actually understand this issue, thanks

**Closed by AllenFang** 2018-01-23 15:44 UTC
