### ISSUE TITLE
Filter get bugged when selection columns is active

### ISSUE THREAD

**Issue by martin-one** [react-bootstrap-table/react-bootstrap-table2#1173] opened 2019-11-19 23:54 UTC
**Describe the bug**
A clear and concise description of what the bug is. In addition, please search issues before you open a report to make sure there's no any duplicated report

**To Reproduce**
In a simple <BootstrapTable/>
add selectRow, filter and filterPosition="top"
Result:

**Screenshots**
![imagen](https://user-images.githubusercontent.com/13110894/69196889-6ec6a980-0af5-11ea-99cc-d3e2e617698b.png)

**codesandbox**
`<BootstrapTable
          keyField="id"
          data={products}
          columns={columns}
          filter={filterFactory()}
          filterPosition="top"
          selectRow={selectedRow}
        />`

``

**Comment by Ymbere** [comment] 2019-11-20 03:40
Hi, didn't found the root cause for the problem yet, but something changed between **v3.2.1** and **3.3.0** that seems to be causing that issue if you need a workaround you can roll back to **v3.21**

### Here is the comparison
#### V3.2.1
[![Edit column-select-test-3.2.1](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/column-select-test-321-xrfwn?fontsize=14&hidenavigation=1&theme=dark)

#### V3.3.1
[![Edit column-select-test-3.3.1](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/column-select-test-331-8g4ge?fontsize=14&hidenavigation=1&theme=dark)

**Comment by AllenFang** [comment] 2019-11-23 08:33
https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/1169

I will fix it ASAP

**Comment by AllenFang** [comment] 2019-12-02 11:57
fixed in `react-bootstrap-table-next@3.3.2`, [RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/12/02/version-bump.html)

**Closed by AllenFang** 2019-12-02 11:57 UTC
