### ISSUE TITLE
styling the row expander

### ISSUE THREAD

**Issue by npomfret** [react-bootstrap-table/react-bootstrap-table2#1338] opened 2020-04-17 16:47 UTC
I'm trying to create a very compact table.  By setting the classes of each column to "p-0" or  `condensed: true`(or some small amount of padding) I get the effect I'm looking for.

However, adding an `expandRow` adds all the padding back again.  I can't figure out to control render of the expand cell.  Any ideas?

[EDIT] actually, adding condensed doesn't appear to have any effect

**Comment by AllenFang** [comment] 2020-04-18 05:53
@npomfret I can't reproduce your problem  I tried to add `condensed` on table and also enable the row expanding feature, but it look good to me...

please give me an online example and please follow the instruction when you open an issue here so that I can help u efficiently 

thanks.  Let's close this issue because I can't reproduce this issue.

**Closed by AllenFang** 2020-04-18 05:53 UTC

**Comment by npomfret** [comment] 2020-04-21 11:00
ok, thanks for checking.  Must be some other style interfering with it.
