### ISSUE TITLE
Cancel EditCell on Pagination

### ISSUE THREAD

**Issue by zoldbogar** [react-bootstrap-table/react-bootstrap-table2#1316] opened 2020-04-03 14:15 UTC
I have a problem with a table2: if I edit a cell on a page and then I change the page, then the same cell on the second page will be in edit mode. We are using an `editorRenderer`.

I found an event for paging: `onPageChange`, but have no idea on how to cancel the edit mode. Please help me out.

Thanks

**Comment by AllenFang** [comment] 2020-04-11 08:59
HI @zoldbogar I can't reproduce this. but I guess this issue shouldn't be happen
because no matter whether you configure `blurToSave` or not, the editor will be resume once the blur occur on the editor.

```js
import BootstrapTable from 'react-bootstrap-table-next';
import cellEditFactory from 'react-bootstrap-table2-editor';

class QualityRanger extends React.Component {
  static propTypes = {
    value: PropTypes.number,
    onUpdate: PropTypes.func.isRequired
  }
  static defaultProps = {
    value: 0
  }
  getValue() {
    return parseInt(this.range.value, 10);
  }
  render() {
    const { value, onUpdate, ...rest } = this.props;
    return [
      <input
        { ...rest }
        key="range"
        ref={ node => this.range = node }
        type="range"
        min="0"
        max="100"
      />,
      <button
        key="submit"
        className="btn btn-default"
        onClick={ () => onUpdate(this.getValue()) }
      >
        done
      </button>
    ];
  }
}

const columns = [{
  dataField: 'id',
  text: 'Product ID'
}, {
  dataField: 'name',
  text: 'Product Name'
}, {
  dataField: 'quality',
  text: 'Product Quality',
  editorRenderer: (editorProps, value, row, column, rowIndex, columnIndex) => (
    <QualityRanger { ...editorProps } value={ value } />
  )
}];

<BootstrapTable
  keyField="id"
  data={ products }
  columns={ columns }
  cellEdit={ cellEditFactory({ mode: 'click', blurToSave: true }) }
  pagination={ paginationFactory() }
/>
```

Above just my simple code. it work well no matter `blurToSave` is true or false. So let me guess if you probably forget to add the `onBlur` props on your custom component so that will cause this issue. But I have no idea to your code.

Let's close it due the not enough information and please share more information(It's better to put your code to the codesandbox and keep it simple and minimal so that I can help u). Thanks

**Closed by AllenFang** 2020-04-11 08:59 UTC

**Comment by zoldbogar** [comment] 2020-04-11 12:00
hello Allen,

thanks for the suggestion, the `{ ...rest }` was missing from our editor component, but adding it did not solve the problem... I have a feeling that there is some other problem with the editor, so for now 
i will copy its code here:
```
import React from 'react';
import PropTypes from 'prop-types';
import { map } from 'lodash';

class DropdownEditor extends React.Component {
  static propTypes = {
    value: PropTypes.number,
    options: PropTypes.array.isRequired,
    onUpdate: PropTypes.func.isRequired,
  };

  getValue() {
    return this.select.options[this.select.selectedIndex].text;
  }

  render() {
    const { value, onUpdate, options, ...rest } = this.props;
    return (
      <select
        { ...rest }
        value={value || ''}
        ref={ node => {
          this.select = node;
        }}
        onChange={() => onUpdate(this.getValue())}
        className="form-control editor edit-select"
      >
        <option value="-1">-- Please Select --</option>
        {map(options, o => (
          <option key={o.value} value={o.value}>
            {o.label}
          </option>
        ))}
      </select>
    );
  }
}

export { DropdownEditor };
```
here is the relevant part of the column definition:
```
  {
    dataField: 'areaName',
    text: 'Area',
    sort: true,
    editable: true,
    editorRenderer: (editorProps, value, row) => (
      <DropdownEditor
        {...editorProps}
        value={row.areaId}
        options={getAreaOptions(props.areas(row.cellId))}
      />
    ),
    filter: selectFilter({
      options: getUniqueValues(data, 'areaName'),
    }),
    hidden: getUniqueValuesAsArray(data, 'areaName').length <= 1,
    headerStyle: { width: '20%' },
  },
```

and here is the table declaration:
```
                          <BootstrapTable
                            {...props.baseProps}
                            striped
                            hover
                            keyField="id"
                            pagination={paginationFactory(paginationOptions)}
                            data={props.baseProps.data}
                            bordered={false}
                            cellEdit={cellEditFactory({
                              mode: 'click',
                              blurToSave: true,
                              afterSaveCell: afterEmployeeSaveCell,
                              beforeSaveCell,
                            })}
                            filter={filterFactory()}
                            defaultSortDirection="asc"
                          />
```

please let me know if you see any other problems here or if I should copy further pieces of code.

Thank you so much,

**Comment by zoldbogar** [comment] 2020-04-11 16:29
Hello Allen,

I am really beginner in React, but I created a small app in sandbox, where the behavior I described is reproducing consistently: https://codesandbox.io/s/adoring-almeida-egdqm?file=/src/App.js

Please open the link I sent you, edit the Quality on the third row (for example) and then change to the second page. You will see then the third row Quality is now in edit mode.

Let me know if you managed to see my problem.
Thanks
